# Install the pre-commit hooks below with
# 'pre-commit install'

# Auto-update the version of the hooks with
# 'pre-commit autoupdate'

# Run the hooks on all files with
# 'pre-commit run --all'

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.0
    hooks:
    -   id: mypy
        files: notebooks/
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args:
        -   --multi-line=3
        -   --trailing-comma
        -   --force-grid-wrap=0
        -   --use-parentheses
        -   --ensure-newline-before-comments
        -   --line-length=88
        files: notebooks/
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black-jupyter
        files: notebooks/
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        files: notebooks/
        args:
        -   --max-line-length=88
        -   --extend-ignore=E203,E501